//------------------------------------------------------------------------------
// <auto-generated>
//     此代码已从模板生成。
//
//     手动更改此文件可能导致应用程序出现意外的行为。
//     如果重新生成代码，将覆盖对此文件的手动更改。
// </auto-generated>
//------------------------------------------------------------------------------

namespace Model
{
    using System;
    using System.Collections.Generic;
    
    public partial class ActivatedLogs
    {
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2214:DoNotCallOverridableMethodsInConstructors")]
        public ActivatedLogs()
        {
            this.ActivatedLogPrescriptions = new HashSet<ActivatedLogPrescriptions>();
        }
    
        public int ActivatedLogId { get; set; }
        public System.DateTime CreateDate { get; set; }
        public Nullable<System.DateTime> ActivatedDate { get; set; }
        public Nullable<int> CommunityUserId { get; set; }
        public bool IsEnable { get; set; }
        public bool IsActivated { get; set; }
        public string Remarks { get; set; }
        public Nullable<int> CommunityId { get; set; }
        public string PhoneNumner { get; set; }
        public string OpenId { get; set; }
        public bool IsFirst { get; set; }
        public Nullable<int> FloorId { get; set; }
        public string Label { get; set; }
        public string DynamicFieId { get; set; }
        public Nullable<int> AuditorId { get; set; }
        public string LabelContent { get; set; }
        public Nullable<int> ActivatedWay { get; set; }
        public Nullable<int> SourceWay { get; set; }
    
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<ActivatedLogPrescriptions> ActivatedLogPrescriptions { get; set; }
        public virtual CommunityEntities CommunityEntities { get; set; }
        public virtual CommunityUsers CommunityUsers { get; set; }
        public virtual Floors Floors { get; set; }
    }
}
