//------------------------------------------------------------------------------
// <auto-generated>
//     此代码已从模板生成。
//
//     手动更改此文件可能导致应用程序出现意外的行为。
//     如果重新生成代码，将覆盖对此文件的手动更改。
// </auto-generated>
//------------------------------------------------------------------------------

namespace Model
{
    using System;
    using System.Collections.Generic;
    
    public partial class ActivatedLogPrescriptions
    {
        public int Id { get; set; }
        public int ActivatedLogId { get; set; }
        public System.DateTime EndDate { get; set; }
        public Nullable<System.DateTime> LastSendDate { get; set; }
        public bool IsEnable { get; set; }
        public bool IsOverdue { get; set; }
        public System.DateTime CreateDate { get; set; }
        public string DoorList { get; set; }
        public int ActivatedState { get; set; }
        public Nullable<System.DateTime> ActivatedDate { get; set; }
        public string Reason { get; set; }
    
        public virtual ActivatedLogs ActivatedLogs { get; set; }
    }
}
