//------------------------------------------------------------------------------
// <auto-generated>
//     此代码已从模板生成。
//
//     手动更改此文件可能导致应用程序出现意外的行为。
//     如果重新生成代码，将覆盖对此文件的手动更改。
// </auto-generated>
//------------------------------------------------------------------------------

namespace Model
{
    using System;
    using System.Collections.Generic;
    
    public partial class AdivserAudits
    {
        public int id { get; set; }
        public int WechatUserId { get; set; }
        public bool IsAudit { get; set; }
        public Nullable<System.DateTime> AuditDateTime { get; set; }
        public System.DateTime CreateDate { get; set; }
        public bool IsEnable { get; set; }
        public string Remark { get; set; }
        public Nullable<int> ArInvitationCodeId { get; set; }
    
        public virtual ARInvitationCodes ARInvitationCodes { get; set; }
        public virtual WechatUsers WechatUsers { get; set; }
    }
}
