//------------------------------------------------------------------------------
// <auto-generated>
//     此代码已从模板生成。
//
//     手动更改此文件可能导致应用程序出现意外的行为。
//     如果重新生成代码，将覆盖对此文件的手动更改。
// </auto-generated>
//------------------------------------------------------------------------------

namespace Model
{
    using System;
    using System.Collections.Generic;
    
    public partial class AdviserAndCommunities
    {
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2214:DoNotCallOverridableMethodsInConstructors")]
        public AdviserAndCommunities()
        {
            this.CommunityEntities = new HashSet<CommunityEntities>();
        }
    
        public int id { get; set; }
        public Nullable<int> CommunityID { get; set; }
        public Nullable<int> CommunityUserID { get; set; }
        public int ReporType { get; set; }
        public int NumberOfDays { get; set; }
        public System.DateTime CreateDate { get; set; }
        public bool IsEnable { get; set; }
        public string Remark { get; set; }
        public string BackstageCommunityUserID { get; set; }
        public string SignID { get; set; }
        public Nullable<System.DateTime> SignDate { get; set; }
        public string CounterpartName { get; set; }
        public string CounterpartPhone { get; set; }
    
        public virtual CommunityUsers CommunityUsers { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<CommunityEntities> CommunityEntities { get; set; }
    }
}
