//------------------------------------------------------------------------------
// <auto-generated>
//     此代码已从模板生成。
//
//     手动更改此文件可能导致应用程序出现意外的行为。
//     如果重新生成代码，将覆盖对此文件的手动更改。
// </auto-generated>
//------------------------------------------------------------------------------

namespace Model
{
    using System;
    using System.Collections.Generic;
    
    public partial class Advisers
    {
        public int id { get; set; }
        public int CommunityUserID { get; set; }
        public string ReportCommunity { get; set; }
        public string SignCommunity { get; set; }
        public Nullable<decimal> Experience { get; set; }
        public System.DateTime CreateDate { get; set; }
        public bool IsEnable { get; set; }
        public string Remark { get; set; }
        public Nullable<decimal> ExperienceUse { get; set; }
        public Nullable<int> WechatUserID { get; set; }
        public bool CanSeeAll { get; set; }
    
        public virtual CommunityUsers CommunityUsers { get; set; }
        public virtual WechatUsers WechatUsers { get; set; }
    }
}
