//------------------------------------------------------------------------------
// <auto-generated>
//     此代码已从模板生成。
//
//     手动更改此文件可能导致应用程序出现意外的行为。
//     如果重新生成代码，将覆盖对此文件的手动更改。
// </auto-generated>
//------------------------------------------------------------------------------

namespace Model
{
    using System;
    using System.Collections.Generic;
    
    public partial class Announcements
    {
        public int AnnouncementId { get; set; }
        public string Title { get; set; }
        public System.DateTime CreateDate { get; set; }
        public bool IsEnable { get; set; }
        public Nullable<System.DateTime> EndDate { get; set; }
        public string Content { get; set; }
        public Nullable<int> CommunityId { get; set; }
        public string Remarks { get; set; }
    
        public virtual CommunityEntities CommunityEntities { get; set; }
    }
}
