//------------------------------------------------------------------------------
// <auto-generated>
//     此代码已从模板生成。
//
//     手动更改此文件可能导致应用程序出现意外的行为。
//     如果重新生成代码，将覆盖对此文件的手动更改。
// </auto-generated>
//------------------------------------------------------------------------------

namespace Model
{
    using System;
    using System.Collections.Generic;
    
    public partial class Authentications
    {
        public int AuthenticationID { get; set; }
        public System.DateTime CreateDate { get; set; }
        public Nullable<System.DateTime> AuthenticationDate { get; set; }
        public Nullable<int> CommunityUserID { get; set; }
        public bool IsEnable { get; set; }
        public bool IsAuthentication { get; set; }
        public Nullable<int> UserID { get; set; }
        public Nullable<int> CommunityID { get; set; }
        public Nullable<int> WechatUserID { get; set; }
        public string Remark { get; set; }
    
        public virtual CommunityEntities CommunityEntities { get; set; }
        public virtual CommunityUsers CommunityUsers { get; set; }
        public virtual Users Users { get; set; }
        public virtual WechatUsers WechatUsers { get; set; }
    }
}
