//------------------------------------------------------------------------------
// <auto-generated>
//     此代码已从模板生成。
//
//     手动更改此文件可能导致应用程序出现意外的行为。
//     如果重新生成代码，将覆盖对此文件的手动更改。
// </auto-generated>
//------------------------------------------------------------------------------

namespace Model
{
    using System;
    using System.Collections.Generic;
    
    public partial class CarAndCommunities
    {
        public int CarAndCommunityID { get; set; }
        public int CommunityID { get; set; }
        public string Title { get; set; }
        public System.DateTime CreateDate { get; set; }
        public string ImgUrl { get; set; }
        public string ContentUrl { get; set; }
        public bool IsEnable { get; set; }
    }
}
