//------------------------------------------------------------------------------
// <auto-generated>
//     此代码已从模板生成。
//
//     手动更改此文件可能导致应用程序出现意外的行为。
//     如果重新生成代码，将覆盖对此文件的手动更改。
// </auto-generated>
//------------------------------------------------------------------------------

namespace Model
{
    using System;
    using System.Collections.Generic;
    
    public partial class CommunityUsers
    {
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2214:DoNotCallOverridableMethodsInConstructors")]
        public CommunityUsers()
        {
            this.ActivatedLogs = new HashSet<ActivatedLogs>();
            this.AdviserAndCommunities = new HashSet<AdviserAndCommunities>();
            this.Advisers = new HashSet<Advisers>();
            this.ARInvitationCodes = new HashSet<ARInvitationCodes>();
            this.Authentications = new HashSet<Authentications>();
            this.DoorOpenLogs = new HashSet<DoorOpenLogs>();
            this.FeedBacks = new HashSet<FeedBacks>();
            this.InvitationLogs = new HashSet<InvitationLogs>();
            this.RedPackets = new HashSet<RedPackets>();
            this.ShopOrders = new HashSet<ShopOrders>();
            this.WechatQrStrScenes = new HashSet<WechatQrStrScenes>();
            this.WechatUsers = new HashSet<WechatUsers>();
        }
    
        public int CommunityUserId { get; set; }
        public Nullable<int> UserId { get; set; }
        public Nullable<int> CommunityId { get; set; }
        public string Remarks { get; set; }
        public bool IsEnable { get; set; }
        public string PhoneNumber { get; set; }
        public string IdNumber { get; set; }
        public string RealName { get; set; }
        public bool IsActivated { get; set; }
        public Nullable<System.DateTime> ActivatedDate { get; set; }
        public string PermissionDoors { get; set; }
        public string Department { get; set; }
        public string Position { get; set; }
        public string Data { get; set; }
        public Nullable<int> FloorID { get; set; }
        public bool IsOwner { get; set; }
        public int ALLIntegral { get; set; }
        public Nullable<System.DateTime> LastDoorOpenTime { get; set; }
        public string ChangeOver { get; set; }
        public bool IsReport { get; set; }
        public string InvitationDoor { get; set; }
        public string RoomNumber { get; set; }
        public int IsAuth { get; set; }
        public double AllRedPacket { get; set; }
        public Nullable<int> AuditNoticeID { get; set; }
        public string HaveCommunityID { get; set; }
        public bool UnreadMessage { get; set; }
    
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<ActivatedLogs> ActivatedLogs { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<AdviserAndCommunities> AdviserAndCommunities { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<Advisers> Advisers { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<ARInvitationCodes> ARInvitationCodes { get; set; }
        public virtual AuditNotices AuditNotices { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<Authentications> Authentications { get; set; }
        public virtual CommunityEntities CommunityEntities { get; set; }
        public virtual Floors Floors { get; set; }
        public virtual Users Users { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<DoorOpenLogs> DoorOpenLogs { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<FeedBacks> FeedBacks { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<InvitationLogs> InvitationLogs { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<RedPackets> RedPackets { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<ShopOrders> ShopOrders { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<WechatQrStrScenes> WechatQrStrScenes { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<WechatUsers> WechatUsers { get; set; }
    }
}
