//------------------------------------------------------------------------------
// <auto-generated>
//     此代码已从模板生成。
//
//     手动更改此文件可能导致应用程序出现意外的行为。
//     如果重新生成代码，将覆盖对此文件的手动更改。
// </auto-generated>
//------------------------------------------------------------------------------

namespace Model
{
    using System;
    using System.Collections.Generic;
    
    public partial class DoorGroups
    {
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2214:DoNotCallOverridableMethodsInConstructors")]
        public DoorGroups()
        {
            this.Doors = new HashSet<Doors>();
        }
    
        public int Id { get; set; }
        public string Name { get; set; }
        public Nullable<int> CommunityId { get; set; }
        public System.DateTime CreDateTime { get; set; }
        public bool IsEnable { get; set; }
    
        public virtual CommunityEntities CommunityEntities { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<Doors> Doors { get; set; }
    }
}
