//------------------------------------------------------------------------------
// <auto-generated>
//     此代码已从模板生成。
//
//     手动更改此文件可能导致应用程序出现意外的行为。
//     如果重新生成代码，将覆盖对此文件的手动更改。
// </auto-generated>
//------------------------------------------------------------------------------

namespace Model
{
    using System;
    using System.Collections.Generic;
    
    public partial class Doors
    {
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2214:DoNotCallOverridableMethodsInConstructors")]
        public Doors()
        {
            this.FloorToDoors = new HashSet<FloorToDoors>();
            this.Machines = new HashSet<Machines>();
        }
    
        public int DoorId { get; set; }
        public string Name { get; set; }
        public Nullable<int> CommunityId { get; set; }
        public Nullable<double> LocationX { get; set; }
        public Nullable<double> LocationY { get; set; }
        public string Remarks { get; set; }
        public bool IsEnable { get; set; }
        public int Distance { get; set; }
        public Nullable<int> WechatQrCodeId { get; set; }
        public Nullable<int> DoorGroupId { get; set; }
        public Nullable<int> DoorTypeId { get; set; }
        public Nullable<int> FloorId { get; set; }
        public Nullable<int> Order { get; set; }
        public Nullable<bool> CanShare { get; set; }
    
        public virtual CommunityEntities CommunityEntities { get; set; }
        public virtual DoorGroups DoorGroups { get; set; }
        public virtual DoorTypes DoorTypes { get; set; }
        public virtual Floors Floors { get; set; }
        public virtual WechatQrCodes WechatQrCodes { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<FloorToDoors> FloorToDoors { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<Machines> Machines { get; set; }
    }
}
