//------------------------------------------------------------------------------
// <auto-generated>
//     此代码已从模板生成。
//
//     手动更改此文件可能导致应用程序出现意外的行为。
//     如果重新生成代码，将覆盖对此文件的手动更改。
// </auto-generated>
//------------------------------------------------------------------------------

namespace Model
{
    using System;
    using System.Collections.Generic;
    
    public partial class DynamicFieIdOfCommunities
    {
        public int Id { get; set; }
        public int CommunityId { get; set; }
        public bool IsEnable { get; set; }
        public bool IsRequired { get; set; }
        public Nullable<int> DynamicContentId { get; set; }
    
        public virtual DynamicContents DynamicContents { get; set; }
    }
}
