//------------------------------------------------------------------------------
// <auto-generated>
//     此代码已从模板生成。
//
//     手动更改此文件可能导致应用程序出现意外的行为。
//     如果重新生成代码，将覆盖对此文件的手动更改。
// </auto-generated>
//------------------------------------------------------------------------------

namespace Model
{
    using System;
    using System.Collections.Generic;
    
    public partial class DynamicContents
    {
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2214:DoNotCallOverridableMethodsInConstructors")]
        public DynamicContents()
        {
            this.DynamicFieIdOfCommunities = new HashSet<DynamicFieIdOfCommunities>();
        }
    
        public int Id { get; set; }
        public int ParentId { get; set; }
        public string FieIdContent { get; set; }
        public string FieIdEnglish { get; set; }
        public int DynamicContentType { get; set; }
    
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<DynamicFieIdOfCommunities> DynamicFieIdOfCommunities { get; set; }
    }
}
