//------------------------------------------------------------------------------
// <auto-generated>
//     此代码已从模板生成。
//
//     手动更改此文件可能导致应用程序出现意外的行为。
//     如果重新生成代码，将覆盖对此文件的手动更改。
// </auto-generated>
//------------------------------------------------------------------------------

namespace Model
{
    using System;
    using System.Collections.Generic;
    
    public partial class InformationContents
    {
        public int InformationContentId { get; set; }
        public System.DateTime CreateDate { get; set; }
        public int InformationTypeId { get; set; }
        public int CommunityId { get; set; }
        public string CoverPhotoUrl { get; set; }
        public string Content { get; set; }
        public bool IsEnable { get; set; }
        public string Remark { get; set; }
        public string ChinaAndEnglishdata { get; set; }
    }
}
