//------------------------------------------------------------------------------
// <auto-generated>
//     此代码已从模板生成。
//
//     手动更改此文件可能导致应用程序出现意外的行为。
//     如果重新生成代码，将覆盖对此文件的手动更改。
// </auto-generated>
//------------------------------------------------------------------------------

namespace Model
{
    using System;
    using System.Collections.Generic;
    
    public partial class Machines
    {
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2214:DoNotCallOverridableMethodsInConstructors")]
        public Machines()
        {
            this.DoorOpenLogs = new HashSet<DoorOpenLogs>();
        }
    
        public int MachineId { get; set; }
        public string InnerNumber { get; set; }
        public Nullable<System.DateTime> LastLoginDate { get; set; }
        public bool IsOnline { get; set; }
        public int Type { get; set; }
        public int Status { get; set; }
        public Nullable<int> DoorId { get; set; }
        public bool IsEnable { get; set; }
        public string Remarks { get; set; }
        public Nullable<int> ModelModelId { get; set; }
        public Nullable<System.DateTime> LastPalpitationDate { get; set; }
    
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<DoorOpenLogs> DoorOpenLogs { get; set; }
        public virtual Doors Doors { get; set; }
        public virtual MachineModels MachineModels { get; set; }
    }
}
