//------------------------------------------------------------------------------
// <auto-generated>
//     此代码已从模板生成。
//
//     手动更改此文件可能导致应用程序出现意外的行为。
//     如果重新生成代码，将覆盖对此文件的手动更改。
// </auto-generated>
//------------------------------------------------------------------------------

namespace Model
{
    using System;
    using System.Collections.Generic;
    
    public partial class RedPacketRules
    {
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2214:DoNotCallOverridableMethodsInConstructors")]
        public RedPacketRules()
        {
            this.CommunityEntities = new HashSet<CommunityEntities>();
        }
    
        public int id { get; set; }
        public float Pre { get; set; }
        public float Next { get; set; }
        public float Odds { get; set; }
        public string Content { get; set; }
        public System.DateTime CreateDate { get; set; }
        public bool IsEnable { get; set; }
        public string Remark { get; set; }
    
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<CommunityEntities> CommunityEntities { get; set; }
    }
}
