//------------------------------------------------------------------------------
// <auto-generated>
//     此代码已从模板生成。
//
//     手动更改此文件可能导致应用程序出现意外的行为。
//     如果重新生成代码，将覆盖对此文件的手动更改。
// </auto-generated>
//------------------------------------------------------------------------------

namespace Model
{
    using System;
    using System.Collections.Generic;
    
    public partial class ShopOrders
    {
        public int ID { get; set; }
        public string ShopOrderID { get; set; }
        public System.DateTime CreateDate { get; set; }
        public bool IsEnable { get; set; }
        public string Remark { get; set; }
        public int Snum { get; set; }
        public int Sprice { get; set; }
        public int StateTYpe { get; set; }
        public int CommunityUserId { get; set; }
        public bool IsActivated { get; set; }
        public Nullable<System.DateTime> ActivatedDate { get; set; }
        public bool IsRead { get; set; }
        public Nullable<int> WechatUserId { get; set; }
        public string ChangeOver { get; set; }
    
        public virtual CommunityUsers CommunityUsers { get; set; }
        public virtual WechatUsers WechatUsers { get; set; }
    }
}
