//------------------------------------------------------------------------------
// <auto-generated>
//     此代码已从模板生成。
//
//     手动更改此文件可能导致应用程序出现意外的行为。
//     如果重新生成代码，将覆盖对此文件的手动更改。
// </auto-generated>
//------------------------------------------------------------------------------

namespace Model
{
    using System;
    using System.Collections.Generic;
    
    public partial class Stories
    {
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2214:DoNotCallOverridableMethodsInConstructors")]
        public Stories()
        {
            this.StoryLogs = new HashSet<StoryLogs>();
        }
    
        public int StoryId { get; set; }
        public string Title { get; set; }
        public string Remarks { get; set; }
        public Nullable<int> StoryTypeId { get; set; }
        public bool IsEnable { get; set; }
        public string ContentUrl { get; set; }
        public string ImgUrl { get; set; }
        public string SimpleConten { get; set; }
    
        public virtual StoryTypes StoryTypes { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<StoryLogs> StoryLogs { get; set; }
    }
}
