//------------------------------------------------------------------------------
// <auto-generated>
//     此代码已从模板生成。
//
//     手动更改此文件可能导致应用程序出现意外的行为。
//     如果重新生成代码，将覆盖对此文件的手动更改。
// </auto-generated>
//------------------------------------------------------------------------------

namespace Model
{
    using System;
    using System.Collections.Generic;
    
    public partial class StoryLogs
    {
        public int StoryLogId { get; set; }
        public long CreateDate { get; set; }
        public string OpenId { get; set; }
        public Nullable<int> UserId { get; set; }
        public string Remarks { get; set; }
        public int StoryLogType { get; set; }
        public Nullable<int> StoryId { get; set; }
    
        public virtual Stories Stories { get; set; }
    }
}
