//------------------------------------------------------------------------------
// <auto-generated>
//     此代码已从模板生成。
//
//     手动更改此文件可能导致应用程序出现意外的行为。
//     如果重新生成代码，将覆盖对此文件的手动更改。
// </auto-generated>
//------------------------------------------------------------------------------

namespace Model
{
    using System;
    using System.Collections.Generic;
    
    public partial class Streets
    {
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2214:DoNotCallOverridableMethodsInConstructors")]
        public Streets()
        {
            this.Villages = new HashSet<Villages>();
        }
    
        public int StreetId { get; set; }
        public string Name { get; set; }
        public int InnerId { get; set; }
        public string SimpleName { get; set; }
        public string Remarks { get; set; }
        public Nullable<int> QuId { get; set; }
    
        public virtual Qus Qus { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<Villages> Villages { get; set; }
    }
}
