//------------------------------------------------------------------------------
// <auto-generated>
//     此代码已从模板生成。
//
//     手动更改此文件可能导致应用程序出现意外的行为。
//     如果重新生成代码，将覆盖对此文件的手动更改。
// </auto-generated>
//------------------------------------------------------------------------------

namespace Model
{
    using System;
    using System.Collections.Generic;
    
    public partial class WechatQrStrScenes
    {
        public int Id { get; set; }
        public string ImgUrl { get; set; }
        public int WechatQrCodeType { get; set; }
        public string Parameter { get; set; }
        public Nullable<int> CommunityUserId { get; set; }
        public long EndDate { get; set; }
        public bool IsUsed { get; set; }
        public string ParameterInfo { get; set; }
    
        public virtual CommunityUsers CommunityUsers { get; set; }
    }
}
