//------------------------------------------------------------------------------
// <auto-generated>
//     此代码已从模板生成。
//
//     手动更改此文件可能导致应用程序出现意外的行为。
//     如果重新生成代码，将覆盖对此文件的手动更改。
// </auto-generated>
//------------------------------------------------------------------------------

namespace Model
{
    using System;
    using System.Collections.Generic;
    
    public partial class WechatUsers
    {
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2214:DoNotCallOverridableMethodsInConstructors")]
        public WechatUsers()
        {
            this.AdivserAudits = new HashSet<AdivserAudits>();
            this.Advisers = new HashSet<Advisers>();
            this.Authentications = new HashSet<Authentications>();
            this.InvitationLogRelations = new HashSet<InvitationLogRelations>();
            this.InvitationLogs = new HashSet<InvitationLogs>();
            this.ShopOrders = new HashSet<ShopOrders>();
        }
    
        public int WechatUserId { get; set; }
        public string OpenId { get; set; }
        public string NickName { get; set; }
        public bool subscribe { get; set; }
        public int Sex { get; set; }
        public string City { get; set; }
        public string Country { get; set; }
        public string Province { get; set; }
        public string Language { get; set; }
        public Nullable<System.DateTime> SubscribeTime { get; set; }
        public string Headimgurl { get; set; }
        public string Remarks { get; set; }
        public Nullable<int> CommunityUserId { get; set; }
        public double LocationX { get; set; }
        public double LocationY { get; set; }
        public Nullable<System.DateTime> LastUploadDate { get; set; }
        public bool IsTem { get; set; }
        public bool IsAdviser { get; set; }
        public string UnionId { get; set; }
    
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<AdivserAudits> AdivserAudits { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<Advisers> Advisers { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<Authentications> Authentications { get; set; }
        public virtual CommunityUsers CommunityUsers { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<InvitationLogRelations> InvitationLogRelations { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<InvitationLogs> InvitationLogs { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<ShopOrders> ShopOrders { get; set; }
    }
}
